# Generated by Django 4.1 on 2023-04-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=255)),
                ('date_of_order', models.DateField(null=True)),
                ('estimated_time_seconds', models.PositiveIntegerField(null=True)),
                ('order_status', models.CharField(choices=[('FINISHED', 'realized'), ('TO_REALIZE', 'to_realize'), ('IN_PROGRESS', 'in_progress')], max_length=11)),
                ('pick_up_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('load_priority', models.CharField(choices=[('AA', 'AA'), ('BB', 'BB'), ('BB', 'CC'), ('CC', 'DD'), ('DD', 'EE')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.order', verbose_name='')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.product', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.warehousezone', verbose_name=''),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.worker', verbose_name=''),
        ),
    ]
