# Generated by Django 3.2.5 on 2023-04-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='productorder',
            name='order_id',
            field=models.ForeignKey(default=22222222, on_delete=django.db.models.deletion.CASCADE, to='magazine.order', verbose_name=''),
            preserve_default=False,
        ),
    ]
